---

- name: Installing Apache, MYSQL DB Community edition & PHP
  yum: 
    name: 
      - httpd
      - mysql-community-server
      - mysql-community-client
      - php 
      - php-mysql
    state: installed

- name: Enabling httpd service and start the service
  service: 
    name: httpd
    enabled: yes
    state: started

- name: Enabling mysql service and start the service
  service: 
    name: mysqld
    enabled: yes
    state: started